spring:
  application:
    name: user-rest-api
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:~/userdata-schema;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
server:
  servlet:
    context-path: /api/v01